### ISSUE TITLE
timestamps are in wrong format

### ISSUE THREAD

**Issue by JensWalter** [apimeister/unpatched-server#24]
if i request all hosts the last_pong field has the wrong timestamp format.
format should be "2023-08-15T19:36:26.766Z"
actually is "2023-08-15 19:29:06"

**Comment by alexkunde** [comment]
@JensWalter the used datetime format is originated in sqlite datetime() function. We can change it to a different base, like the iso8601 from json.

**Comment by JensWalter** [comment]
timestamps need to be in iso format, once because the openapi spec says so, and the browser also wants it in this format.
