### ISSUE TITLE
Upload artifacts to DTZ artifact page

### ISSUE THREAD

**Issue by alexkunde** [apimeister/unpatched-server#41]
example:  

  - name: dtz upload
      uses: DownToZero-cloud/objectstore-upload@main
      with:
        api_key: ${{ secrets.DTZ_API_KEY }}
        context_id: ${{ secrets.DTZ_CONTEXT_ID }}
        object_key: dtz-red
        name: target/x86_64-unknown-linux-musl/release/dtz-red

**Comment by JensWalter** [comment]
I added the secrets to the repo, I will add you as dtz admin for the context within the week.
